ExamPreparation/Exam/Bookmarks/Bookmarks/Bookmarks.App/Models/ViewModels/BookmarkViewModel.cs
namespace Bookmarks.App.Models.ViewModels
{
    using Bookmarks.Common.Mappings;
    using Bookmarks.Models;

    public class BookmarkViewModel : IMapFrom<Bookmark>
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }
    }
}

ExamPreparation/Exam/Bookmarks/Bookmarks/Bookmarks.App/Controllers/BookmarksController.cs
namespace Bookmarks.App.Controllers
{
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    using AutoMapper;
    using AutoMapper.QueryableExtensions;

    using Bookmarks.App.Models.BindingModels;
    using Bookmarks.App.Models.ViewModels;
    using Bookmarks.Data.UnitOfWork;
    using Bookmarks.Models;

    using PagedList;

    using System.Web.Mvc.Expressions;

    using Microsoft.AspNet.Identity;

    [Authorize]
    public class BookmarksController : BaseController
    {
        public BookmarksController(IBookmarksData data)
            : base(data)
        {
        }

        [AllowAnonymous]
        public ActionResult Index(int? page)
        {
            var bookmarks = this.Data.Bookmarks
                .All()
                .OrderBy(b => b.Title)
                .ProjectTo<BookmarkViewModel>()
                .ToPagedList(page ?? 1,6);

            return View(bookmarks);
        }

        // GET: Bookmarks
        public ActionResult Details(int id)
        {
            var bookmark = this.Data.Bookmarks
                .All()
                .Include(x => x.Votes)
                .FirstOrDefault(x => x.Id == id);
            var bookmarkViewModel = Mapper.Map<BookmarkDetailsViewModel>(bookmark);

            var userId = this.User.Identity.GetUserId();
            bookmarkViewModel.UserHasVoted = bookmark.Votes.Any(x => x.UserId == userId);
            return this.View(bookmarkViewModel);
        }

        [HttpGet]
        public ActionResult Create()
        {
            this.LoadCategories();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BookmarkBindingModel model)
        {
            if (model != null && this.ModelState.IsValid)
            {
                var bookmark = Mapper.Map<Bookmark>(model);
                this.Data.Bookmarks.Add(bookmark);
                this.Data.SaveChanges();
                return this.RedirectToAction(x => x.Details(bookmark.Id));
            }

            this.LoadCategories();

            return this.View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddComment(CommentBindingModel model)
        {
            if (model != null && this.ModelState.IsValid)
            {
                model.UserId = this.User.Identity.GetUserId();
                var comment = Mapper.Map<Comment>(model);
                this.Data.Comments.Add(comment);
                this.Data.SaveChanges();

                var commentDb = this.Data.Comments
                    .All()
                    .Where(x => x.Id == comment.Id)
                    .ProjectTo<CommentViewModel>()
                    .FirstOrDefault();

                return this.PartialView("DisplayTemplates/CommentViewModel", commentDb);
            }

            return this.Json("Error");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteComment(int commentId)
        {
            var comment = this.Data.Comments
                .All()
                .FirstOrDefault(x => x.Id == commentId);
            if (comment != null && comment.UserId == this.User.Identity.GetUserId())
            {
                this.Data.Comments.Delete(comment);
                this.Data.SaveChanges();

                return this.Content(string.Empty);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Can not delete the comment");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Vote(int bookmarkId)
        {
            var bookmark = this.Data.Bookmarks
                .All()
                .FirstOrDefault(x => x.Id == bookmarkId);

            if (bookmark != null)
            {
                var userHasVoted = bookmark.Votes.Any(x => x.UserId == this.User.Identity.GetUserId());
                if (!userHasVoted)
                {
                    this.Data.Votes.Add(new Vote
                    {
                        BookmarkId = bookmark.Id,
                        UserId = this.User.Identity.GetUserId(),
                        Value = 1
                    });
                    this.Data.SaveChanges();
                }

                var votesCount = bookmark.Votes.Sum(x => x.Value);
                return this.Content(votesCount.ToString());
            }

            return new EmptyResult();
        }

        private void LoadCategories()
        {
            this.ViewBag.Categories = this.Data.Categories
               .All()
               .Select(x => new SelectListItem
               {
                   Value = x.Id.ToString(),
                   Text = x.Name
               });
        }
    }
}

ExamPreparation/Exam/Bookmarks/Bookmarks/Bookmarks.App/Views/Bookmarks/Create.cshtml
@model Bookmarks.App.Models.BindingModels.BookmarkBindingModel

@{
    ViewBag.Title = "Create Bookmark";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    @Html.LabelFor(x => x.Title)
    @Html.EditorFor(x => x.Title)
    @Html.ValidationMessageFor(x => x.Title)
    <br/>
    @Html.LabelFor(x => x.Url)
    @Html.EditorFor(x => x.Url)
    @Html.ValidationMessageFor(x => x.Url)
    <br/>
    @Html.LabelFor(x => x.Description)
    @Html.EditorFor(x => x.Description)
    @Html.ValidationMessageFor(x => x.Description)
    <br/>
    @Html.LabelFor(x => x.CategoryId)
    @Html.DropDownListFor(x => x.CategoryId, (IEnumerable<SelectListItem>)ViewBag.Categories)
    @Html.ValidationMessageFor(x => x.CategoryId)
    <br/>
    <input type="submit" name="submit" value="Add Bookmark"/>
}

@section scripts{
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

ExamPreparation/Exam/Bookmarks/Bookmarks/Bookmarks.App/Views/Bookmarks/Details.cshtml
@using System.CodeDom
@model Bookmarks.App.Models.ViewModels.BookmarkDetailsViewModel

@{
    ViewBag.Title = "Bookmark details";
}

<h2>@Model.Title</h2>

<div>
    <p>@Html.DisplayNameFor(x => x.Url): @Html.DisplayFor(x => x.Url)</p>
    <p>@Html.DisplayNameFor(x => x.CategoryName): @Html.DisplayFor(x => x.CategoryName)</p>
    <p>@Html.DisplayNameFor(x => x.Description): @Html.DisplayFor(x => x.Description)</p>
</div>

<div id="comments">
    <h2>Comments</h2>
    @if (Model.Comments.Any())
    {
        @Html.DisplayFor(x => x.Comments)
    }
    else
    {
        <span>No comments</span>
    }
</div>

<div id="votes" class="pull-right">
    <div>
        Votes: <span id="votes-count">@Model.Votes</span>
        @if (!Model.UserHasVoted)
        {
            <div id="vote-button">
                @using (Ajax.BeginForm("Vote", "Bookmarks", new { bookmarkId = Model.Id }, new AjaxOptions()
                {
                    HttpMethod = "POST",
                    UpdateTargetId = "votes-count",
                    InsertionMode = InsertionMode.Replace,
                    OnSuccess = "onVoteSuccess"
                }))
                {
                    @Html.AntiForgeryToken()
                    <input type="submit" name="name" value="+" />
                }
            </div>
        }

    </div>
</div>

<div>
    <h2>Add comment</h2>
    @using (Ajax.BeginForm("AddComment", "Bookmarks", new { bookmarkId = Model.Id }, new AjaxOptions()
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.InsertAfter,
        UpdateTargetId = "comments",
        OnSuccess = "onAddCommentSuccess"
    }))
    {
        @Html.AntiForgeryToken()
        <input type="text" id="content" name="content" value=""/>
        <input type="submit" name="submit" value="Add comment" />
    }
</div>

@section scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        function onAddCommentSuccess() {
            document.getElementById("content").value = '';
        }

        function onVoteSuccess() {
            var button = document.getElementById("vote-button");
            button.parentNode.removeChild(button);
        }
    </script>
}

ExamPreparation/Exam/Bookmarks/Bookmarks/Bookmarks.App/Views/Bookmarks/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<Bookmarks.App.Models.ViewModels.BookmarkViewModel>

@{
    ViewBag.Title = "All Bookmarks";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    @Html.DisplayFor(x => x)
</div>
@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))